version: "3.8"

services:
  fastapi:
    build: .
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PYTHONPATH=/app
    networks:
      - backend

  celery_worker:
    build: .
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    command: celery -A app.celery_worker worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis      
    environment:
      - PYTHONPATH=/app
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - backend

networks:
  backend:
    driver: bridge
